# url для скачивания исходников go
go_url_base:  "https://golang.org/dl"
go_proxy_url: "https://proxy.golang.org"

# Версии go которые нужно собрать
# обрати внимание, что go компиляторы собираются последовательно один за другим
# так как каждый следующий компилятор использует предыдущий для сборки
# в итоге для сборки компонентов kubernates используется последний go компилятор
# после добавления новой версии go компилятора в этот список
# все компоненты kubernetes будут собираться этим новым компилятором
go_versions:
  - version: "1.4"
    dockerfile: "Dockerfile-1.4.j2"
  - version: "1.17.13"
    dockerfile: "Dockerfile.j2"
  - version: "1.20.6"
    dockerfile: "Dockerfile.j2"
  - version: "1.22.6"
    dockerfile: "Dockerfile.j2"
  - version: "1.24.5"
    dockerfile: "Dockerfile.j2"

# локальная директория для артефактов
artifact_dir_local:     "./artifacts"
# директория для загрузки исходников
artifact_dir_src_local: "{{ artifact_dir_local }}/src"
# директория для загрузки артефактов сборки
artifact_dir_bin_local: "{{ artifact_dir_local }}/bin"

# удаленная директория для артефактов
artifact_dir_remote:    "/tmp/ansible"
# директория для загрузки исходников
artifact_dir_src_remote: "{{ artifact_dir_remote }}/src"
# директория для загрузки артефактов сборки
artifact_dir_bin_remote: "{{ artifact_dir_remote }}/bin"

# URL для скачивания исходников etcd
etcd_base_url: https://github.com/etcd-io/etcd.git
# Версии etcd которые нужно собрать
etcd_version_tags:
  - version: "v3.4.9"
    dockerfile: "Dockerfile-3.4.j2"
  - version: "v3.6.4"
    dockerfile: "Dockerfile-3.6.j2"
