# Runtime-образ Go: компилятор установлен в систему (/usr/local/go).
# Использование: FROM golang-astra:1.24.5-runtime

ARG BUILD_IMAGE
ARG BASE_IMAGE=astra-linux:2.12

FROM ${BUILD_IMAGE} AS build

FROM ${BASE_IMAGE}

COPY --from=build /out/usr/local/go /usr/local/go

ENV GOROOT=/usr/local/go
ENV PATH="/usr/local/go/bin:${PATH}"
