# Runtime-образ Go: компилятор установлен в систему (/usr/local/go).
# Зависимость: golang:VERSION-build (build-образ с Go в /out/usr/local/go/)
#
# Использование: FROM golang:1.24.5-runtime-build
#   go version   → go version go1.24.5 linux/amd64

ARG GOLANG_IMAGE
ARG BASE_IMAGE=astra-linux:2.12

FROM ${GOLANG_IMAGE} AS build

FROM ${BASE_IMAGE}

COPY --from=build /out/usr/local/go /usr/local/go

ENV GOROOT=/usr/local/go
ENV PATH="/usr/local/go/bin:${PATH}"
