FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y \
    bash \
    build-essential \
    curl \
    ca-certificates \
    tar \
    git \
&& rm -rf /var/lib/apt/lists/*

# Копируем архив внутрь контейнера
COPY {{ archive_src }} /app/src/

# Распаковываем
RUN tar -xzf /app/src/{{ archive_src }} -C /app/src --strip-components=1

# Компилируем Go (папка /app/src/src корректна, там лежат исходники)
WORKDIR /app/src/src

RUN export GOPROXY="{{ go_proxy_url }}" \
    && export CGO_ENABLED=0 \
    && sed -i '/"-Werror",/d' cmd/dist/build.c \
    && ./make.bash \
    && mkdir -p /app/bin \
    && tar -czf "/app/bin/{{ archive_bin }}" -C /app/src bin pkg src
