# Runtime-образ dpkg: статический dpkg установлен в систему.
# Использование: FROM dpkg-astra:1.23.5-runtime

ARG BUILD_IMAGE=dpkg-astra:1.23.5-build
ARG BASE_IMAGE=astra-linux:2.12

FROM ${BUILD_IMAGE} AS build

FROM ${BASE_IMAGE}

COPY --from=build /out /
