# Основной цикл - обработка каждой версии Go последовательно
- name: loop go build all versions
  include_tasks: build-version.yml
  loop: "{{ go_versions }}"
  loop_control:
    loop_var: build_version
