# playbooks/build.yml
- name: Build src
  hosts: docker_build
  become: true
  roles:
    - { role: build-go, tags: ['build-go'] }
    - { role: build-etcd, tags: ['build-etcd'] }
    - { role: build-containerd, tags: ['build-containerd'] }
    - { role: build-runc, tags: ['build-runc'] }
    - { role: build-kubernetes, tags: ['build-kubernetes'] }
    - { role: build-cni, tags: ['build-cni'] }
  vars_files:
    - ../group_vars/all.yml
